apiVersion: v1
kind: Pod
metadata:
  name: secure-pod-template
  labels:
    app: secure-app
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: secure-container
      image: your-image:latest
      imagePullPolicy: Always
      command: ["your-app"]
      args: ["--secure-mode"]
      resources:
        limits:
          memory: "256Mi"
          cpu: "500m"
        requests:
          memory: "128Mi"
          cpu: "250m"
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
        privileged: false                   # ❗ Explicitly disable privileged mode
      volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
      ports:
        - containerPort: 8080
          protocol: TCP
  volumes:
    - name: config-volume
      configMap:
        name: secure-config
  restartPolicy: Always
  dnsPolicy: ClusterFirst
  hostNetwork: false
  hostPID: false                           # ❗ Prevent sharing host PID namespace
  hostIPC: false                           # ❗ Prevent sharing host IPC namespace
  automountServiceAccountToken: false
